[package]
name = "branch-prediction"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-coding-challenges = { path = "../../" }
rand = "0.8"
rand_chacha = "0.3"

# Optional: for more detailed benchmarking
criterion = { version = "0.5", optional = true }

[dev-dependencies]
criterion = "0.5"
