[package]
name = "rust-coding-challenges"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "challenges/branch-prediction", "challenges/simple-cas", "challenges/simple-parser" , "challenges/wc-command"]

[dependencies]
